### PR TITLE
KZOO-151: Fields missing in call recording request for URL based recordings vs 4.3

### PR DESCRIPTION
**Pull request by holy-batman**
In the request sent for recordings to 3rd party URLs, there are some fields that are missing in 5.0 compared to 4.3. Those are owner_id, start, duration_ms and recording_id

### CODE REVIEW

**Review by lazedo — CHANGES_REQUESTED** [review]
try to use https://github.com/2600hz/kazoo/blob/4.3/core/kazoo_call/src/kzc_recording.erl#L606-L618
for explicitness

**Comment by holy-batman** [comment]
> try to use https://github.com/2600hz/kazoo/blob/4.3/core/kazoo_call/src/kzc_recording.erl#L606-L618
> for explicitness

done!

**Review by lazedo — APPROVED** [review]

**Comment by lazedo** [comment]
@holy-batman backport to 5.0 branch please

**Comment by holy-batman** [comment]
@lazedo done https://github.com/2600hz/kazoo-media-mgr/pull/14 sry my internet went down so took a bit longer.

**Pull request merged**
